UPSTREAM_KIBANA_HOST = "intpkibana01.prod.switch.internal:5601"
UPSTREAM_ELASTICSEARCH_HOST = "intpelasticslb01.prod.switch.internal"
UPSTREAM_ELASTICSEARCH_PORT = 9200
KIBANA_INDEX = ".kibana4"

CLOSE_INDEXES_BY_TIMEOUT = false

REDIS_SERVER = "localhost"
REDIS_PORT = 6379
INDEX_TIMEOUT = 600